# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    - "client/**/*"
    - "tmp/**/*"

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/SpaceAroundOperators:
  Enabled: true
